set(CMAKE_SYSTEM_NAME Crescent)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_FIND_ROOT_PATH $ENV{QPKG_SYSROOT_DIR})
set(CMAKE_SYSROOT $ENV{QPKG_SYSROOT_DIR})

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_AR llvm-ar)

set(CMAKE_C_COMPILER_TARGET x86_64-unknown-crescent)
set(CMAKE_CXX_COMPILER_TARGET x86_64-unknown-crescent)
set(CMAKE_ASM_COMPILER_TARGET x86_64-unknown-crescent)

set(CMAKE_C_FLAGS "-fdiagnostics-color")
set(CMAKE_CXX_FLAGS "-fdiagnostics-color")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

