[binaries]
c = 'x86_64-crescent-gcc'
cpp = 'x86_64-crescent-g++'
ar = 'x86_64-crescent-ar'
strip = 'x86_64-crescent-strip'
pkgconfig = 'x86_64-crescent-pkg-config'

[host_machine]
system = 'crescent'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
