[general]
target = "x86_64-unknown-crescent"
sysroot = "sysroot"
recipes_dir = "recipes"
host_recipes_dir = "host-recipes"
meta_dir = "meta"
build_root = "build"
arch = "x86_64"
kernel_toolchain = "x86_64_clang"
prefer_binaries = true

[build]
cc = "clang"
cxx = "clang++"
cflags = "-pipe"
cxxflags = "-pipe"
ldflags = "-fuse-ld=lld"

