[general]
target = "x86_64-unknown-crescent"
sysroot = "sysroot_x86_64"
recipes_dir = "recipes"
host_recipes_dir = "host-recipes"
meta_dir = "meta"
build_root = "build_x86_64"
arch = "x86_64"
kernel_toolchain = "x86_64_clang"
prefer_binaries = false

[host]
cc = "clang"
cxx = "clang++"
cflags = "-pipe"
cxxflags = "-pipe"
ldflags = "-fuse-ld=lld"

[target]
cc = "@BUILDROOT@/../scripts/clang-wrapper"
cxx = "@BUILDROOT@/../scripts/clang-wrapper++"
cflags = "-pipe"
cxxflags = "-pipe"
ldflags = "-fuse-ld=lld"

