[general]
name = "system-cc"
version = "20.0.0"
src = [
	"https://github.com/llvm/llvm-project/archive/e59582b6f8f1be3e675866f6a5d661eb4c8ed448.tar.gz"
]
binary_alternative = "system-cc-bin"
depends = ["hzlibc"]
workdir = "llvm-project-e59582b6f8f1be3e675866f6a5d661eb4c8ed448"

[configure]
args = [[
	"cmake",
	"-GNinja",
	"-DCMAKE_BUILD_TYPE=Release",
	"-DCMAKE_C_COMPILER=clang",
	"-DCMAKE_CXX_COMPILER=clang++",
	"-DCMAKE_INSTALL_PREFIX=@DESTDIR@",
	"-DLLVM_ENABLE_PROJECTS=\"clang;lld\"",
	"-DLLVM_ENABLE_RUNTIMES=\"compiler-rt;libunwind;libcxxabi;libcxx\"",
	"-DLLVM_TARGETS_TO_BUILD=\"X86;AArch64\"",
	"-DLLVM_DEFAULT_TARGET_TRIPLE=@TARGET@",
	"-DLLVM_ENABLE_LLD=ON",
	"-DLLVM_INCLUDE_BENCHMARKS=OFF",
	"-DLLVM_INCLUDE_DOCS=OFF",
	"-DLLVM_INCLUDE_EXAMPLES=OFF",
	"-DLLVM_INCLUDE_TESTS=OFF",
	"-DDEFAULT_SYSROOT=@SYSROOT@",
	"-DCLANG_BUILD_TOOLS=OFF",
	"-DCLANG_DEFAULT_OBJCOPY=llvm-objcopy",
	"-DCLANG_DEFAULT_UNWINDLIB=libunwind",
	"-DCLANG_INCLUDE_DOCS=OFF",
	"-DCLANG_INCLUDE_TESTS=OFF",
	"-DLIBCXXABI_ENABLE_THREADS=OFF",
	"-DLIBCXXABI_USE_COMPILER_RT=ON",
	"-DCRESCENT=ON",
	"-DLIBCXX_ENABLE_FILESYSTEM=OFF",
	"@SRCDIR@/llvm"
]]

[build]
args = [["ninja"]]

[install]
args = [
	["ninja", "install"],
	# todo not sure why is this needed
	["cp", "bin/clang-20", "@DESTDIR@/bin/clang-20"],
	["ln", "-sf", "clang-20", "@DESTDIR@/bin/clang"]
]

